Tests
makarovaiuliia/stellar-burger pull request #2
Opened 2024-04-27 14:05 UTC by makarovaiuliia

2024-04-27 16:38 UTC, ArslanMustafin requested changes
## Code Review

Здравствуйте!

Отличная работа. 🔥

### **Вы молодец!**

- Сборка и запуск проекта выполняются без ошибок;
- Все юнит-тесты проходят успешно;
- Все Cypress тесты проходят успешно;

### **Но есть несколько замечаний, которые нужно исправить:**

- Отметил небольшие замечание в коде.

### **Замечания можно лучше, необязательный к исправлению.**

2024-04-27 16:38 UTC, ArslanMustafin commented on src/services/constructorSlice.test.ts
> +  it('should handle addIngredient (not a bun)', () => {
**Надо исправить:**
Т.к. у вас есть условие в экшене `addIngredient`, то вы должны протестировать 2 варианта событий:
- когда добавляется ингредиент;
- когда добавляется булка; - вам нужно добавить тест на булку.

2024-04-27 16:38 UTC, ArslanMustafin commented on src/services/store.test.ts
> +  it('should initialize with the correct default state', () => {
**Надо исправить:**

по чек-листу требуется написать тест, проверяющий правильную настройку и работу rootReducer: вызов rootReducer с undefined состоянием и экшеном, который не обрабатывается ни одним редьюсером (например, { type: 'UNKNOWN_ACTION' }), возвращает корректное начальное состояние хранилища.

вот пример:

```js
  it('handles unknown action correctly', () => {
    const fakeAction = { type: 'UNKNOWN_ACTION' };
    const state = rootReducer(undefined, fakeAction);
    expect(state).toEqual({
      burgerConstructor: constructorReducer(undefined, fakeAction),
      feed: feedReducer(undefined, fakeAction),
      ingredients: ingredientsReducer(undefined, fakeAction),
      order: orderReducer(undefined, fakeAction),
      orders: ordersReducer(undefined, fakeAction),
      user: userReducer(undefined, fakeAction)
    });
  });
```

2024-04-27 16:38 UTC, ArslanMustafin commented on src/services/userSlice.test.ts
> +};
**Можно лучше:**

Можно не мокать все эти данные, вам ведь важно проверить работу самих редьюсеров.  https://redux.js.org/usage/writing-tests#unit-testing-individual-functions

ниже привёл пару примеров как это нужно делать)

```js
  it('should set loginUserRequest to true and loginUserError to null when loginUser.pending is dispatched', () => {
    const expectedState: TUserState = {
      ...initialState,
      loginUserRequest: true
    };

    const actualState = userReducer(
      {
        ...initialState,
        loginUserError: { success: true, message: 'Test Error' }
      },
      loginUser.pending('', userRegData)
    );

    expect(actualState).toEqual(expectedState);
  });

  it('should update state with orders data and set loginUserRequest to false when loginUser.fulfilled is dispatched', () => {
    const expectedState: TUserState = {
      ...initialState,
      data: userTestData,
      isAuthChecked: true
    };

    const actualState = userReducer(
      {
        ...initialState,
        loginUserRequest: true
      },
      loginUser.fulfilled(userTestData, '', userRegData)
    );
```

2024-04-27 16:38 UTC, ArslanMustafin commented on src/utils/burger-api.ts
> +      console.log(data);
**Можно лучше:**

Лучше удалить все console.log, alert и debugger, которые используются во время отладки.

2024-04-27 16:38 UTC, ArslanMustafin commented on cypress/e2e/constructor.cy.ts
> +    cy.visit('http://localhost:4000');
**Надо исправить:**

лучше вынести базовый адрес сервера в конфиг cypress.

<https://docs.cypress.io/guides/references/best-practices#Setting-a-Global-baseUrl>

2024-04-27 16:38 UTC, ArslanMustafin commented on cypress/e2e/constructor.cy.ts
> +    cy.intercept('GET', 'https://norma.nomoreparties.space/api/ingredients', {
**Можно лучше:**

тут можно просто написать `api/ingredients`, вторым параметром в intercept передается регулярное выражение, поэтому полностью url можно не писать

2024-04-27 16:38 UTC, ArslanMustafin commented on cypress/e2e/orderCreation.cy.ts
> +    cy.get('button[type="submit"]').click();
**Можно лучше:**

лучше использовать моки токенов, что бы не проходить авторизацию, т.к. иначе тест проверяет слишком много функционала помимо самого создания заказа.

2024-05-03 14:30 UTC, makarovaiuliia commented on src/services/userSlice.test.ts
> +};
Добрый день! Спасибо вам большое за ревью! Я пока исправила все, что было "надо исправить", чтобы зачесть работу. Я обязательно исправлю все "можно лучше", но чуть позже, так как я сейчас в отпуске. Спасибо еще раз вам за правки!

2024-05-20 15:54 UTC, merged